





import "./globals.css";
import { Outfit } from "next/font/google";
import type { Metadata } from "next";
import "@/src/style/user.css"
import { SidebarProvider } from "@/src/context/sidebar-context";



const outfit = Outfit({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`${outfit.className}`}
      >
       
   
      <SidebarProvider >{children}</SidebarProvider>
     
  


      </body>
    </html>
  );
}
